org: devparam
app: modern-centrix
service: modern-centrix-be
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handlers/userHandler.getAllCompanies
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-offline
